### ISSUE TITLE
Passing empty string to parse raises fatal error

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#3]
### What?
If you pass an empty string to the `parse` method, it breaks.

Example:
```js
parser.parse('');
```

It looks like it's related to the Go parser though as I see Go stuff:

```
fatal error: out of memory

runtime stack:
runtime.throw(0x1054503bc, 0xd)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:617 +0x72
runtime.largeAlloc(0xffffffffffffffff, 0xc000020100, 0xc000000600)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/malloc.go:1043 +0x186
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x7fff5fbf1d70)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/proc.go:1153

goroutine 17 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:311 fp=0xc000497cb0 sp=0xc000497ca8 pc=0x1050571c0
runtime.mallocgc(0xffffffffffffffff, 0x0, 0xc0000baa00, 0x1)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/malloc.go:949 +0x872 fp=0xc000497d50 sp=0xc000497cb0 pc=0x10500d8d2
runtime.rawbyteslice(0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/string.go:272 +0xa1 fp=0xc000497d90 sp=0xc000497d50 pc=0x1050471f1
runtime.stringtoslicebyte(0x0, 0x104014720, 0xffffffffffffffff, 0x1054549e9, 0x19, 0xc000497e48)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/string.go:161 +0xb5 fp=0xc000497dd8 sp=0xc000497d90 pc=0x105046bc5
main.Parse(0x104014720, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/Users/fmvilas/www/parser/cparser/cparser.go:20 +0x5f fp=0xc000497e58 sp=0xc000497dd8 pc=0x10537a11f
main._cgoexpwrap_6ca36088b704_Parse(0x104014720, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:86 +0x70 fp=0xc000497e90 sp=0xc000497e58 pc=0x10537a000
runtime.call64(0x0, 0x7fff5fbf1dc0, 0x7fff5fbf1e58, 0x28)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:520 +0x3b fp=0xc000497ee0 sp=0xc000497e90 pc=0x1050575fb
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/cgocall.go:314 +0x177 fp=0xc000497f58 sp=0xc000497ee0 pc=0x105004e87
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/cgocall.go:191 +0xc5 fp=0xc000497fc0 sp=0xc000497f58 pc=0x105004c75
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:773 +0x9b fp=0xc000497fe0 sp=0xc000497fc0 pc=0x105058b4b
runtime.goexit()
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000497fe8 sp=0xc000497fe0 pc=0x105059271
```

**Comment by fmvilas** [comment]
It's fixed on the new parser. Closing.
