### ISSUE TITLE
Undeclared dependencies error under Yarn PnP

### ISSUE THREAD

**Issue by gabormagyar** [asyncapi/parser-js#733]
#### Describe the bug
[Yarn PnP](https://yarnpkg.com/features/pnp) needs all dependencies to be declared. This causes an error at runtime when the parser tries to access the following dependencies that are not declared in the [manifest](https://github.com/asyncapi/parser-js/blob/next-major/package.json#L44).

Example:
> Error: @asyncapi/parser tried to access @stoplight/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

The workaround is to add the undeclared dependencies to the user package's `.yarnrc.yml` file like so:

```yaml
packageExtensions:
  "@asyncapi/parser@*":
    dependencies:
      "@stoplight/types": "^13.9.1"
      "@stoplight/json": "^3.20.2"
      "@stoplight/spectral-ref-resolver": "^1.0.3"
      "@stoplight/json-ref-readers": "^1.2.2"
```

The solution is to add these as dependencies or peerDependencies (optional or otherwise).

#### How to Reproduce
Install and run the parser under [Yarn PnP](https://yarnpkg.com/features/pnp) package manager

#### Full errors with call stack:

<details>

<summary>@stoplight/types</summary>

```
Error: @asyncapi/parser tried to access @stoplight/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @stoplight/types
Required by: @asyncapi/parser@npm:2.0.0-next-major.15 (via /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/)

Require stack:
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/AsyncAPIInputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/InputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/AbstractGenerator.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/generate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/program.js
    at Function.require$$0.Module._resolveFilename (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22559:13)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22413:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/index.js:18:17)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22603:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22443:14)
```

Offending line seems to be this one: https://github.com/asyncapi/parser-js/blob/next-major/src/index.ts#L1
</details>

<details>
<summary>@stoplight/json</summary>

```
Error: @asyncapi/parser tried to access @stoplight/json, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @stoplight/json
Required by: @asyncapi/parser@npm:2.0.0-next-major.15 (via /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/utils/)

Require stack:
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/utils/mergeTraits.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/utils/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/v2/functions/channelParameters.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/v2/ruleset.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/v2/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/spectral.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/validate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parse.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parser.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/AsyncAPIInputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/InputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/AbstractGenerator.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/generate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/program.js
    at Function.require$$0.Module._resolveFilename (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22570:13)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22424:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/ruleset/utils/mergeTraits.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22614:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22454:14)
```

Offending line seems to be this one: https://github.com/asyncapi/parser-js/blob/next-major/src/ruleset/utils/mergeTraits.ts#L1
</details>

<details>
<summary>@stoplight/spectral-ref-resolver</summary>

```
Error: @asyncapi/parser tried to access @stoplight/spectral-ref-resolver, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @stoplight/spectral-ref-resolver
Required by: @asyncapi/parser@npm:2.0.0-next-major.15 (via /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/)

Require stack:
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/resolver.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/spectral.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/validate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parse.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parser.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/AsyncAPIInputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/InputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/AbstractGenerator.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/generate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/program.js
    at Function.require$$0.Module._resolveFilename (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22572:13)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22426:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/resolver.js:13:33)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22616:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22456:14)
```

Offending line seems to be this one: https://github.com/asyncapi/parser-js/blob/next-major/src/resolver.ts#L1
</details>

<details>
<summary>@stoplight/json-ref-readers</summary>

```
Error: @asyncapi/parser tried to access @stoplight/json-ref-readers, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @stoplight/json-ref-readers
Required by: @asyncapi/parser@npm:2.0.0-next-major.15 (via /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/)

Require stack:
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/resolver.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/spectral.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/validate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parse.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/parser.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/AsyncAPIInputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/InputProcessor.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/processors/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/AbstractGenerator.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/generators/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-modelina-npm-2.0.0-next.4-52848d6dc3-f26a0e0414.zip/node_modules/@asyncapi/modelina/lib/cjs/index.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/generate.js
- /Users/mg/WebstormProjects/mbh/asyncapi-generator/build/src/program.js
    at Function.require$$0.Module._resolveFilename (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22574:13)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22428:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.yarn/cache/@asyncapi-parser-npm-2.0.0-next-major.15-54e6ea0b35-2502272baa.zip/node_modules/@asyncapi/parser/cjs/resolver.js:15:28)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22618:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/Users/mg/WebstormProjects/mbh/asyncapi-generator/.pnp.cjs:22458:14)

```

Offending line seems to be this one: https://github.com/asyncapi/parser-js/blob/next-major/src/resolver.ts#L2
</details>

**Comment by woylie** [comment]
I don't have any additional details, but this is definitely still an issue.

**Comment by derberg** [comment]
ping @magicmatatjahu @smoya - can you have a look?

**Comment by smoya** [comment]
I couldn't reproduce the issue. I used the following code:

```ts
import { Parser, Diagnostic, fromFile, DiagnosticSeverity } from '@asyncapi/parser';

const parser = new Parser();
function prettyPrint(diagnostics: Diagnostic[]) {
    for (const diagnostic of diagnostics) {
      if (diagnostic.severity === DiagnosticSeverity.Error) {
        console.log(diagnostic.severity, 'ERR', diagnostic.message);
      } else {
        console.log(diagnostic.severity, diagnostic.message);
      }
    }
}

const parse = async () => {
    console.log("Done");
    const { document, diagnostics } = await fromFile(parser, './asyncapi.yaml').parse();
    prettyPrint(diagnostics);
};

parse();
```

`yarn.lock` has the `stoplight/types` in it 🤔 
However, I agree any dependency the parser directly relies on, should be in the package.json 👍

Anyway, Is there anything I need to do to reproduce the issue?

**Comment by woylie** [comment]
> Anyway, Is there anything I need to do to reproduce the issue?

You can try something like this:

```bash
mkdir asynctest
cd asynctest
yarn init -2
echo "nodeLinker: pnp" >> .yarnrc.yml
yarn add @asyncapi/generator @asyncapi/html-template
```

Then add this to `package.json`:

```json
{
  "scripts": {
    "asyncapi": "ag asyncapi.yml @asyncapi/html-template"
  }
}
```

And finally, run:

```bash
yarn asyncapi
```

That returns:

```
/Users/me/asynctest/.pnp.cjs:18059
      Error.captureStackTrace(firstError);
            ^

Error: @asyncapi/parser tried to access @stoplight/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @stoplight/types
Required by: @asyncapi/parser@npm:2.1.0 (via /Users/me/asynctest/.yarn/cache/@asyncapi-parser-npm-2.1.0-7f076f680b-ed29f26851.zip/node_modules/@asyncapi/parser/cjs/)

Require stack:
- /Users/me/asynctest/.yarn/cache/@asyncapi-parser-npm-2.1.0-7f076f680b-ed29f26851.zip/node_modules/@asyncapi/parser/cjs/index.js
- /Users/me/asynctest/.yarn/cache/@asyncapi-generator-npm-1.14.0-d18a56be3f-2df02b19fb.zip/node_modules/@asyncapi/generator/cli.js
    at require$$0.Module._resolveFilename (/Users/me/asynctest/.pnp.cjs:18059:13)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at require$$0.Module._load (/Users/me/asynctest/.pnp.cjs:17948:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/me/asynctest/.yarn/cache/@asyncapi-parser-npm-2.1.0-7f076f680b-ed29f26851.zip/node_modules/@asyncapi/parser/cjs/index.js:18:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (/Users/me/asynctest/.pnp.cjs:18103:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

After adding the `packageExtension` lines from the first post, it works (or at least, the error above disappears; there's a [separate issue in html-template 1.0.0](https://github.com/asyncapi/html-template/issues/454) at the moment).

**Comment by smoya** [comment]
@woylie thanks for sharing! I could finally reproduce it. The important piece was to set the linker to pnp (as in your example) 👍 . 
Additionally, yarn website mentions the issue we are facing as a good feature in pnp: https://yarnpkg.com/features/pnp#ghost-dependencies-protection

@woylie @gabormagyar any of you happy to create a PR with the fix?
