### ISSUE TITLE
Payload property named message breaks with null value

### ISSUE THREAD

**Issue by ly29** [asyncapi/parser-js#863]
**Payload property named message breaks with null value**

```        "payload": {
          "type": "object",
          "properties": {
            "message": {
              "type": ["string", "null"],
              "maxLength": 50
            }
          },
          "required": ["message"],
        },
        "examples": [{
            "name": "return",
            "payload": {
              "message": null
            }
          }
        ]
      }
```

It breaks rendering of the asyncapi spec, validation does not give valid errors and studio.asyncapi.com breaks

**Expected result**
It works and renders. Note that this works if the message property is renamed or given a non null example value.

**Actual result**

The following error is given 
```
	Error thrown during AsyncAPI document validation. Name: Error, message: jsonPath: Cannot read properties of null (reading 'schemaFormat'): _$_property === 'message' && _$_v.schemaFormat === void 0, stack: Error: jsonPath: Cannot read properties of null (reading 'schemaFormat'): _$_property === 'message' && _$_v.schemaFormat === void 0 at v._eval (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4494941) at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4491179 at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493697 at Array.forEach (<anonymous>) at v._walk (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493676) at v._trace (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4491130) at v._trace (https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4490522) at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4490621 at https://studio.asyncapi.com/static/js/main.f7f7093d.js:2:4493697 at Array.forEach (<anonymous>)
```

**Steps to reproduce**

Paste the following gist into the asyncapi studio
https://gist.github.com/ly29/6b56cc8252ad48ac681f19ea468d540f

**Troubleshooting**
I have reduced the issue down to one specific property that breaks.

**Comment by ly29** [comment]
Yeah it was not clear to me where to report, thank you taking care of that.

**Comment by ly29** [comment]
So this looks like a bug to me. Any pointers to where to fix. Should be a reasonably small fix I imagine...

**Comment by jonaslagoni** [comment]
Without being 100% sure, I think its https://github.com/asyncapi/parser-js/blob/0a765c1ed46af605707d9e37f71d76192b950602/src/ruleset/v2/ruleset.ts#L119 that might be complaining.

**Comment by tarunspandit** [comment]
Hi maintainers — I would like to be considered for this issue under the 2026-08 Microgrant Program, if it remains available after the round is finalized.

My proposed approach is:

1. add a minimal regression fixture where an object has a nullable property named `message` and the example value is `null`;
2. trace the ruleset/JSONPath callback that assumes every `message` value exposes `schemaFormat`;
3. guard the null/non-schema case narrowly, without suppressing valid diagnostics for actual message objects;
4. verify the original null case, a non-null string value, and the same schema with a renamed property; and
5. add v2/v3 coverage if the affected ruleset is shared across specification versions.

I understand assignment is at the maintainers' discretion, and I will wait for confirmation before opening a PR. Is this approach aligned with the intended fix?

**Comment by kishansinghifs1** [comment]
Hiii @AayushSaini101 can I work on this ?

**Comment by tzh476** [comment]
Implement and verified a fix. Root cause: several v2-ruleset `given` selectors navigate `@property === "message"` without a `!@null` guard, so when a payload object has a nullable property literally named `message` (e.g. `message: null`), the JSONPath reads `.schemaFormat`/`.oneOf` on `null` and crashes validation. Fix: add `!@null &&` to those selectors in `ruleset/v2/ruleset.ts` (schemaFormat, payload default/examples, oneOf) and `ruleset/v2/functions/messageExamples-spectral-rule-v2.ts`. Verified: the OP example validates with no error diagnostic; full ruleset/validate suite passes (43 suites / 244 tests). Happy to open the PR when assigned for the microgrant round; otherwise the same change can be applied by whoever is assigned. Thanks.
